version: '3'

volumes:
  node_modules:

services:

  mariadb:
    image: mariadb:10.5.1
    # command:  # 起動コマンド
    container_name: mokumoku-mariadb
    expose:
      - '3306'
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_DATABASE: mokumoku
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: controller
      MYSQL_PASSWORD: controller
    # restart: always
    volumes:
      # - ./db/data:/var/lib/mysql # SQL ; 二回目起動時以降にmigrationが行われないため，こいつは無効化しておく
      - ./db/migration:/docker-entrypoint-initdb.d  # SQL Migrations

  python:
    build: ./server
    command: python api/main.py
    container_name: mokumoku-python
    depends_on:
      - mariadb
    environment:
      TZ: 'Asia/Tokyo'
      GOOGLE_APPLICATION_CREDENTIALS: '/key.json'
      DB_USER: controller
      DB_PASSWORD: controller
      SERVER_ENV: 'development'
    expose:
      - '8081'
    ports:
      - '8081:8081'  # 開発試験用
    links:
      - mariadb:mariadb
    # restart: always
    volumes:
      - ./server/src:/src
      - ./server/key.json:/key.json:ro

  vue:
    build: ./client
    # command:  # 起動コマンド
    container_name: mokumoku-vue
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - '8080:8080'
      # - '8443:433'
    links:
      - python:python
    # restart: always
    volumes:
      - ./client/src:/app
      - node_modules:/app/node_modules
