version: '3'

services:

  mariadb:
    image: mariadb:10.5.1
    container_name: mokumoku-mariadb
    expose:
      - '3306'
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_DATABASE: mokumoku
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: controller
      MYSQL_PASSWORD: controller
    restart: always

  python:
    image: tomo9925/kakemori_server:develop
    container_name: mokumoku-python
    depends_on:
      - mariadb
    environment:
      TZ: 'Asia/Tokyo'
      GOOGLE_APPLICATION_CREDENTIALS: '/key.json'
      DB_USER: controller
      DB_PASSWORD: controller
      SERVER_ENV: 'development'
    expose:
      - '8081'
    links:
      - mariadb:mariadb
    restart: always

  vue:
    image: tomo9925/kakemori_vue:develop
    container_name: mokumoku-vue
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - '443:8080'
    links:
      - python:python
    restart: always
