FROM python:3.8.2

WORKDIR /src

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY ./src ./
COPY ./key.json /

ENV GOOGLE_APPLICATION_CREDENTIALS='/key.json' DB_HOST='mokumoku-db.mariadb.database.azure.com' DB_USER='controller@mokumoku-db' DB_PASSWORD='CJLC6jRSP2vP' SERVER_ENV='development' SERVER_HOST='0.0.0.0' SERVER_PORT='80'
CMD ["python", "api/main.py"]
