name: pull request verify

on:
  pull_request:
    branches: 
      - Develop

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:
    name: verify build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose build
        run: |
          docker-compose build
